// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOP4Z76R-mkbMEoi6L3sEpNwEXtB5RnU',
    appId: '1:749143264627:web:e7723764eb772eab07c906',
    messagingSenderId: '749143264627',
    projectId: 'mobile-car-spa-e23de',
    authDomain: 'mobile-car-spa-e23de.firebaseapp.com',
    storageBucket: 'mobile-car-spa-e23de.firebasestorage.app',
    measurementId: 'G-C34YMZ5JFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1WSlrGYMIKPAfZ0ihHumXxC7k_tWjnI',
    appId: '1:749143264627:android:6239869a8d115e8807c906',
    messagingSenderId: '749143264627',
    projectId: 'mobile-car-spa-e23de',
    storageBucket: 'mobile-car-spa-e23de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3fSR6YDIIY_wKFz42lMdFRdEB7kOlBs',
    appId: '1:749143264627:ios:0d37d7798d887f8d07c906',
    messagingSenderId: '749143264627',
    projectId: 'mobile-car-spa-e23de',
    storageBucket: 'mobile-car-spa-e23de.firebasestorage.app',
    iosBundleId: 'com.example.mobileCarSpaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn3fSR6YDIIY_wKFz42lMdFRdEB7kOlBs',
    appId: '1:749143264627:ios:0d37d7798d887f8d07c906',
    messagingSenderId: '749143264627',
    projectId: 'mobile-car-spa-e23de',
    storageBucket: 'mobile-car-spa-e23de.firebasestorage.app',
    iosBundleId: 'com.example.mobileCarSpaNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOP4Z76R-mkbMEoi6L3sEpNwEXtB5RnU',
    appId: '1:749143264627:web:bb9619624041ed2307c906',
    messagingSenderId: '749143264627',
    projectId: 'mobile-car-spa-e23de',
    authDomain: 'mobile-car-spa-e23de.firebaseapp.com',
    storageBucket: 'mobile-car-spa-e23de.firebasestorage.app',
    measurementId: 'G-PSYHZX7RKP',
  );
}
