import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/staff_management_screen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// Screens
import 'screens/splash_screen.dart';
import 'screens/splash_login_screen.dart'; // Update if renamed
import 'screens/dashboard_screen.dart';
import 'screens/report_screen.dart';
import 'screens/vehicle_catalog_screen.dart';
import 'screens/service_management_screen.dart';
import 'screens/expense_screen.dart';
import 'screens/view_enquiries_screen.dart';
import 'screens/add_enquiry_screen.dart';
import 'screens/settings_screen.dart';

// Staff feature screens
import 'features/staff/staff_list_screen.dart';
import 'features/staff/staff_detail_screen.dart';
import 'features/staff/attendance/staff_attendance_screen.dart';
import 'features/staff/payroll/staff_payroll_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = ThemeData(
      colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
      useMaterial3: true,
      visualDensity: VisualDensity.adaptivePlatformDensity,
    );

    return MaterialApp(
      title: 'Mobile Car Spa',
      debugShowCheckedModeBanner: false,
      theme: theme,
      
      initialRoute: '/',
      routes: {
        // Startup
        '/': (_) => const SplashScreen(),
        '/login': (_) => const SplashLoginScreen(),

        // Core
        '/dashboard': (_) => const DashboardScreen(),

        // Enquiries
        '/view-enquiries': (_) => const ViewEnquiriesScreen(),
        '/add-enquiry': (_) => const AddEnquiryScreen(),

        // Expenses
        '/expenses': (_) => const ExpenseScreen(),

        // Catalog / Services
        '/vehicle-catalog': (_) => const VehicleCatalogScreen(),
        '/service-management': (_) => const ServiceManagementScreen(),

        // Reports
        '/report': (_) => const ReportScreen(),

        // Settings
        '/settings': (_) => const SettingsScreen(),

        // Staff feature
        '/staff-list': (_) => const StaffListScreen(),
        // For screens with params (StaffDetail, Attendance, Payroll), use Navigator.push with MaterialPageRoute
        '/staff-management': (_) => const StaffManagementScreen(),
      },

      onUnknownRoute: (settings) => MaterialPageRoute<void>(
        builder: (_) => const DashboardScreen(),
      ),
    );
  }
}
